version: 2
updates:
  # GitHub workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Sophon package
  - package-ecosystem: pip
    directory: "libs/python/sophon"
    schedule:
      interval: "weekly"
