# Common hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

# Sophon package
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: '^libs/python/sophon/.*\.py'
        args: [ --settings-path, ./libs/python/sophon/pyproject.toml ]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        files: '^libs/python/sophon/.*\.py'
        args: [ --config, ./libs/python/sophon/pyproject.toml ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        files: '^libs/python/sophon/.*\.py'
      - id: ruff-format
        files: '^libs/python/sophon/.*\.py'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: '^libs/python/sophon/.*\.py'
        args: [ --config-file, libs/python/sophon/pyproject.toml, libs/python/sophon/src/sophon/ ]
        pass_filenames: false
